# spring.cloud.config.label 指明远程仓库的分支
# spring.cloud.config.profile:
# dev：开发环境配置文件；test：测试环境；pro：正式环境
# spring.cloud.config.uri 指明配置服务中心的网址
# spring.cloud.config.discovery.enable 从配置中心读取文件
# spring.cloud.config.discovery.serviceId 配置中心的serviceId,即服务名
# 在读取配置文件时不写ip地址，而是直接写服务名，如果这时配置服务部署多份，通过负载均衡，可以达到高可用
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: cw
    password: password
server:
  port: 8882
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]