# zipkin+sleuth配置参数：
# spring.zipkin.baseUrl:指定server-zipkin的服务地址，可以通过ip来指定，也可以通过服务名指定
# spring.sleuth.sampler.percentage:设置采样率，为了测试设置100%采集
server:
  port: 8988
spring:
  application:
    name: zipkin-hi
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
#      base-url: http://server-zipkin/
    sleuth:
      sampler:
        percentage: 1